### ISSUE TITLE
Error in list command

### ISSUE THREAD

**Issue by CGarces** [CGarces/pop2owa#11]
LIST command return a size of 0 bytes.
Email clients like popcorn need this size to work.

Reported by: idcarlos

**Comment by CGarces** [comment]
Logged In: YES 
user_id=795313

This issue has fixed in the official release
The bug is now closed

Original comment by: idcarlos

**Comment by CGarces** [comment]
- **status**: open --> closed-fixed

Original comment by: idcarlos

**Comment by linuxjackto1** [comment]
thanks www.movied.org
