### ISSUE TITLE
Bug with big attachments

### ISSUE THREAD

**Issue by CGarces** [CGarces/pop2owa#12]
When try to download a message with a big file included
(more than 1MB) , the program may fail.

Marked with high priority but I can't fix it at the moment

Pop2owa download the entire file and then send the file
to the client. I need find the way to download the file
incrementally and send to the client program in chunks

Reported by: idcarlos

**Comment by CGarces** [comment]
- **priority**: 9 --> 5
- **status**: open --> pending-postponed

Original comment by: idcarlos

**Comment by CGarces** [comment]
Logged In: YES 
user_id=1312539

This Tracker item was closed automatically by the system. It was
previously set to a Pending status, and the original submitter
did not respond within 14 days (the time period specified by
the administrator of this Tracker).

Original comment by: sf-robot

**Comment by CGarces** [comment]
- **status**: pending-postponed --> closed-postponed

Original comment by: sf-robot

**Comment by CGarces** [comment]
Logged In: YES 
user_id=795313

With very big attachment (more than 5MB) the CPU grow to
100%. Not is a POP2OWA bug, the cause of the CPU usage is
the MSXML library. I'm looking for a solution.

Original comment by: idcarlos

**Comment by CGarces** [comment]
- **status**: closed-postponed --> open-postponed

Original comment by: idcarlos

**Comment by CGarces** [comment]
Logged In: YES 
user_id=795313

I can't fix (at the moment) this bug.
The problem now, it's a "timeout" when the attachment it's big.
The better way to avoid this it's changing the time out of
you email client to a high value.

Original comment by: idcarlos

**Comment by CGarces** [comment]
- **status**: open-postponed --> closed-wont-fix

Original comment by: idcarlos

**Comment by CGarces** [comment]
Logged In: YES 
user_id=795313

This issue has fixed in the official release
The bug is now closed

Original comment by: idcarlos

**Comment by CGarces** [comment]
- **status**: closed-wont-fix --> closed-fixed

Original comment by: idcarlos

**Comment by linuxjackto1** [comment]
thanks www.movied.org
