### ISSUE TITLE
Error unencoding body

### ISSUE THREAD

**Issue by CGarces** [CGarces/pop2owa#13]
Messages with Content-Transfer-Encoding like base64 or
Quoted-Printable fails.

Outlook Web Access send the message unencoded, as plain
text. POP2OWA must ignore the Content-Transfer-Encoding
header.

This bug is fixed in CVS and It will be closed in the
next release.

Reported by: idcarlos

**Comment by CGarces** [comment]
Logged In: YES 
user_id=795313

This issue has fixed in the official release
The bug is now closed

Original comment by: idcarlos

**Comment by CGarces** [comment]
- **status**: open --> closed-fixed

Original comment by: idcarlos

**Comment by linuxjackto1** [comment]
thanks www.movied.org
